import { Providers } from '@/providers'
import { Layout } from 'antd'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'
import { PageHeader } from '../components/PageHeader'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Recipes APP',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <Layout className="layout">
            <PageHeader>{children}</PageHeader>
          </Layout>
        </body>
      </Providers>
    </html>
  )
}
